In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Data Preprocessing

In [3]:
dataset=pd.read_csv('Final_dataset_CS.csv',header=1)
print(dataset.shape)
dataset = dataset.drop(dataset.columns[[0,1,2]], axis=1)
dataset.head()

(445, 42)

,GGBS_kg_m3,GGBS_CaO_%,GGBS_SiO2_%,GGBS_Al2O3_%,GGBS_MgO_%,GGBS_Fe2O3_%,GGBS_SO3_%,FlyAsh_kg_m3,FA_CaO_%,FA_SiO2_%,...,Superplasticizer_%,SiO2 to Na2O (silicate modulus),Curing_Temperature,Relative Humidity,Condition,Length (mm),Breadth (mm),height (mm),CS 7 day (Mpa),CS 28 day (Mpa)
0,0.0,47.75,27.17,8.6,3.89,0.42,1.45,650.0,15.48,48.43,...,0.64,2.5,23.0,60.0,Ambient,150.0,150.0,150.0,NaN,29.00
1,650.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,0.64,2.5,23.0,60.0,Ambient,150.0,150.0,150.0,NaN,40.00
2,325.0,47.75,27.17,8.6,3.89,0.42,1.45,325.0,15.48,48.43,...,0.64,2.5,23.0,60.0,Ambient,150.0,150.0,150.0,NaN,45.00
3,0.0,47.75,27.17,8.6,3.89,0.42,1.45,637.0,15.48,48.43,...,0.64,2.5,23.0,60.0,Ambient,150.0,150.0,150.0,NaN,48.00
4,637.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,0.64,2.5,23.0,60.0,Ambient,150.0,150.0,150.0,NaN,50.32

In [4]:
dataset['Water (kg/m3)'] = pd.to_numeric(dataset['Water (kg/m3)'], errors='coerce')
dataset.dtypes

GGBS_kg_m3                          float64
GGBS_CaO_%                          float64
GGBS_SiO2_%                         float64
GGBS_Al2O3_%                        float64
GGBS_MgO_%                          float64
GGBS_Fe2O3_%                        float64
GGBS_SO3_%                          float64
FlyAsh_kg_m3                        float64
FA_CaO_%                            float64
FA_SiO2_%                           float64
FA_Al2O3_%                          float64
FA_MgO_%                            float64
FA_Fe2O3_%                          float64
FA_SO3_%                            float64
SF_kg_m3                            float64
SF_CaO_%                            float64
SF_SiO2_%                           float64
SF_Al2O3_%                          float64
SF_MgO_%                            float64
SF_Fe2O3_%                          float64
SF_SO3_%                            float64
Total NaOH (kg in 1m3 mix)          float64
Concentration (M) NaOH              float64
Total Na2SiO3 (kg in 1m3 of mix)    float64
Coarse Aggregate (kg/m3)            float64
Fine Aggregates (kg/m3)             float64
Water (kg/m3)                       float64
Activator_Binder_Ratio              float64
Water_Binder_Ratio                  float64
Superplasticizer_%                  float64
SiO2 to Na2O (silicate modulus)     float64
Curing_Temperature                  float64
Relative Humidity                   float64
Condition                               str
Length (mm)                         float64
Breadth (mm)                        float64
height (mm)                         float64
CS 7 day (Mpa)                      float64
CS 28 day (Mpa)                     float64
dtype: object

In [5]:
from sklearn.preprocessing import LabelEncoder 

le = LabelEncoder()
dataset['Condition'] = le.fit_transform(dataset['Condition'])

In [6]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')
dataset = dataset.copy()
dataset[:] = imputer.fit_transform(dataset)
dataset.head()

,GGBS_kg_m3,GGBS_CaO_%,GGBS_SiO2_%,GGBS_Al2O3_%,GGBS_MgO_%,GGBS_Fe2O3_%,GGBS_SO3_%,FlyAsh_kg_m3,FA_CaO_%,FA_SiO2_%,...,Superplasticizer_%,SiO2 to Na2O (silicate modulus),Curing_Temperature,Relative Humidity,Condition,Length (mm),Breadth (mm),height (mm),CS 7 day (Mpa),CS 28 day (Mpa)
0,0.0,47.75,27.17,8.6,3.89,0.42,1.45,650.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,29.00
1,650.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,40.00
2,325.0,47.75,27.17,8.6,3.89,0.42,1.45,325.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,45.00
3,0.0,47.75,27.17,8.6,3.89,0.42,1.45,637.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,48.00
4,637.0,47.75,27.17,8.6,3.89,0.42,1.45,0.0,15.48,48.43,...,0.64,2.5,23.0,60.0,0,150.0,150.0,150.0,34.0,50.32

In [7]:
(dataset.isnull().mean())*100

GGBS_kg_m3                          0.0
GGBS_CaO_%                          0.0
GGBS_SiO2_%                         0.0
GGBS_Al2O3_%                        0.0
GGBS_MgO_%                          0.0
GGBS_Fe2O3_%                        0.0
GGBS_SO3_%                          0.0
FlyAsh_kg_m3                        0.0
FA_CaO_%                            0.0
FA_SiO2_%                           0.0
FA_Al2O3_%                          0.0
FA_MgO_%                            0.0
FA_Fe2O3_%                          0.0
FA_SO3_%                            0.0
SF_kg_m3                            0.0
SF_CaO_%                            0.0
SF_SiO2_%                           0.0
SF_Al2O3_%                          0.0
SF_MgO_%                            0.0
SF_Fe2O3_%                          0.0
SF_SO3_%                            0.0
Total NaOH (kg in 1m3 mix)          0.0
Concentration (M) NaOH              0.0
Total Na2SiO3 (kg in 1m3 of mix)    0.0
Coarse Aggregate (kg/m3)            0.0
Fine Aggregates (kg/m3)             0.0
Water (kg/m3)                       0.0
Activator_Binder_Ratio              0.0
Water_Binder_Ratio                  0.0
Superplasticizer_%                  0.0
SiO2 to Na2O (silicate modulus)     0.0
Curing_Temperature                  0.0
Relative Humidity                   0.0
Condition                           0.0
Length (mm)                         0.0
Breadth (mm)                        0.0
height (mm)                         0.0
CS 7 day (Mpa)                      0.0
CS 28 day (Mpa)                     0.0
dtype: float64

In [8]:
plt.figure(figsize=(30,20))
sns.heatmap(dataset.corr(), annot=True, cmap='coolwarm')
plt.savefig('correlation_plot.png', dpi=300)
plt.close()

## Model

In [9]:
dataset.head()
dataset.to_csv('new_ds.csv', index=False)